version: '3.8'

services:
  mjml:
    build:
      context: .
      dockerfile: docker/mjml/Dockerfile
    container_name: app_mjml
    environment:
      LOG_LEVEL: ${MJML_LOG_LEVEL:-info}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000
      HOST: 0.0.0.0
    expose:
      - "3000"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge
